export interface PolicyTemplate {
  id: string;
  name: string;
  description: string;
  category: string;
  type: string;
  conditions: Record<string, unknown>;
  rules: Record<string, unknown>;
}

export const policyTemplates: PolicyTemplate[] = [
  {
    id: 'tpl-monthly-budget-1000',
    name: 'Monthly Budget Cap ($1,000)',
    description: 'Block transactions when monthly spend exceeds $1,000',
    category: 'spending-limits',
    type: 'budget',
    conditions: { transactionType: ['agent-to-agent', 'agent-to-merchant'] },
    rules: { maxMonthlyBudget: 1000, period: 'monthly' },
  },
  {
    id: 'tpl-monthly-budget-5000',
    name: 'Monthly Budget Cap ($5,000)',
    description: 'Block transactions when monthly spend exceeds $5,000',
    category: 'spending-limits',
    type: 'budget',
    conditions: { transactionType: ['agent-to-agent', 'agent-to-merchant'] },
    rules: { maxMonthlyBudget: 5000, period: 'monthly' },
  },
  {
    id: 'tpl-per-tx-limit-10',
    name: 'Per-Transaction Limit ($10)',
    description: 'Block any single transaction over $10',
    category: 'spending-limits',
    type: 'transaction',
    conditions: {},
    rules: { maxAmount: 10 },
  },
  {
    id: 'tpl-per-tx-limit-50',
    name: 'Per-Transaction Limit ($50)',
    description: 'Block any single transaction over $50',
    category: 'spending-limits',
    type: 'transaction',
    conditions: {},
    rules: { maxAmount: 50 },
  },
  {
    id: 'tpl-per-tx-limit-100',
    name: 'Per-Transaction Limit ($100)',
    description: 'Block any single transaction over $100',
    category: 'spending-limits',
    type: 'transaction',
    conditions: {},
    rules: { maxAmount: 100 },
  },
  {
    id: 'tpl-block-social-media',
    name: 'Block Social Media Scraping',
    description: 'Deny scraping requests targeting social media sites (LinkedIn, Facebook, Twitter, Instagram)',
    category: 'content-restrictions',
    type: 'purpose',
    conditions: {},
    rules: { blockedDomains: ['linkedin.com', 'facebook.com', 'twitter.com', 'x.com', 'instagram.com'], action: 'deny' },
  },
  {
    id: 'tpl-url-allowlist',
    name: 'URL Allowlist',
    description: 'Only permit scraping from pre-approved domains',
    category: 'content-restrictions',
    type: 'purpose',
    conditions: {},
    rules: { allowedDomains: ['example.com'], mode: 'allowlist' },
  },
  {
    id: 'tpl-business-hours-only',
    name: 'Business Hours Only',
    description: 'Only allow transactions during business hours (9 AM - 6 PM UTC, weekdays)',
    category: 'time-based',
    type: 'time',
    conditions: {},
    rules: { allowedHoursUTC: { start: 9, end: 18 }, allowedDays: ['mon', 'tue', 'wed', 'thu', 'fri'] },
  },
  {
    id: 'tpl-no-weekends',
    name: 'No Weekend Transactions',
    description: 'Block all transactions on Saturday and Sunday',
    category: 'time-based',
    type: 'time',
    conditions: {},
    rules: { blockedDays: ['sat', 'sun'] },
  },
  {
    id: 'tpl-rate-limit-10-per-hour',
    name: 'Rate Limit (10/hour)',
    description: 'Limit to 10 payment executions per hour per org',
    category: 'rate-limiting',
    type: 'transaction',
    conditions: {},
    rules: { maxTransactionsPerHour: 10 },
  },
  {
    id: 'tpl-merchant-blocklist',
    name: 'Merchant Blocklist',
    description: 'Block payments to specific providers/merchants',
    category: 'merchant-control',
    type: 'merchant',
    conditions: {},
    rules: { blockedMerchants: ['risky-provider'], action: 'deny' },
  },
  {
    id: 'tpl-require-callback',
    name: 'Require Webhook Callback',
    description: 'Deny payments that do not specify a callback_url for real-time notification',
    category: 'compliance',
    type: 'transaction',
    conditions: {},
    rules: { requireCallbackUrl: true },
  },
  {
    id: 'tpl-max-daily-spend-500',
    name: 'Daily Spend Cap ($500)',
    description: 'Limit daily spending to $500',
    category: 'spending-limits',
    type: 'budget',
    conditions: {},
    rules: { maxDailyBudget: 500, period: 'daily' },
  },
  {
    id: 'tpl-scraping-only',
    name: 'Scraping Actions Only',
    description: 'Only allow "scrape" and "search" actions, block all others',
    category: 'action-control',
    type: 'agent',
    conditions: {},
    rules: { allowedActions: ['scrape', 'search'], mode: 'allowlist' },
  },
  {
    id: 'tpl-geo-block-gov',
    name: 'Block Government Domains',
    description: 'Block scraping of .gov and .mil domains',
    category: 'content-restrictions',
    type: 'purpose',
    conditions: {},
    rules: { blockedDomainSuffixes: ['.gov', '.mil'], action: 'deny' },
  },
  {
    id: 'tpl-composite-budget-and-hours',
    name: 'Budget + Business Hours',
    description: 'Composite: $5,000/month budget AND business hours only',
    category: 'composite',
    type: 'composite',
    conditions: {},
    rules: {
      operator: 'AND',
      policies: [
        { type: 'budget', rules: { maxMonthlyBudget: 5000 } },
        { type: 'time', rules: { allowedHoursUTC: { start: 9, end: 18 }, allowedDays: ['mon', 'tue', 'wed', 'thu', 'fri'] } },
      ],
    },
  },
];
