openapi: 3.1.0

info:
  title: Agentic Commerce Shopping API
  description: API for policy-enforced product discovery and purchasing from Etsy
  version: 1.0.0

servers:
  - url: https://census-mono-implemented-catch.trycloudflare.com

security:
  - BearerAuth: []

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token for authentication

  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
          example: mock-1
        title:
          type: string
          example: Handmade Leather Notebook - Brown
        description:
          type: string
          example: Beautiful handcrafted leather notebook
        price:
          type: number
          example: 35.99
        currency:
          type: string
          example: USD
        merchant:
          type: string
          example: ArtisanLeatherCo
        merchantId:
          type: string
          example: shop-123
        url:
          type: string
          example: https://etsy.com/listing/mock-1
        imageUrl:
          type: string
          example: https://via.placeholder.com/300
        category:
          type: string
          example: Paper & Party Supplies
        inStock:
          type: boolean
          example: true

    PolicyCheckResult:
      type: object
      properties:
        allowed:
          type: boolean
          example: true
        reason:
          type: string
          example: Budget exceeded
        matchedPolicies:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              name:
                type: string
              passed:
                type: boolean
              reason:
                type: string

    SpendingInfo:
      type: object
      properties:
        userId:
          type: string
        spending:
          type: object
          properties:
            daily:
              type: number
            weekly:
              type: number
            monthly:
              type: number
        limits:
          type: array
          items:
            type: object

paths:
  /api/products/search:
    post:
      operationId: searchProducts
      summary: Search for products
      description: Search products based on keywords and price
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - query
              properties:
                query:
                  type: string
                  description: Search keywords (e.g., "luxury purse", "leather notebook")
                max_price:
                  type: number
                  description: Maximum price in USD
                category:
                  type: string
                  description: Product category
                limit:
                  type: integer
                  default: 10
                  description: Number of results to return
      responses:
        "200":
          description: Search results
          content:
            application/json:
              schema:
                type: object
                properties:
                  products:
                    type: array
                    items:
                      $ref: "#/components/schemas/Product"

  /api/policy/check:
    post:
      operationId: checkPolicy
      summary: Check purchase policy
      description: Verify if a purchase is allowed based on company policies
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - user_id
                - product_id
                - price
                - merchant
              properties:
                user_id:
                  type: string
                  description: User identifier
                product_id:
                  type: string
                  description: Product identifier
                price:
                  type: number
                  description: Product price in USD
                merchant:
                  type: string
                  description: Merchant/shop name
                category:
                  type: string
                  description: Product category
      responses:
        "200":
          description: Policy check result
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PolicyCheckResult"

  /api/policy/spending:
    post:
      operationId: getUserSpending
      summary: Get user spending
      description: Get user's spending information for different time periods
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - user_id
              properties:
                user_id:
                  type: string
                  description: User identifier
      responses:
        "200":
          description: Spending information
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SpendingInfo"

  /api/checkout/initiate:
    post:
      operationId: initiateCheckout
      summary: Start checkout
      description: Initiate a Stripe checkout session for a product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - user_id
                - product_id
                - amount
                - product_name
                - merchant
              properties:
                user_id:
                  type: string
                  description: User identifier
                product_id:
                  type: string
                  description: Product identifier from search results
                product_name:
                  type: string
                  description: Name of the product
                amount:
                  type: number
                  description: Purchase amount in USD
                merchant:
                  type: string
                  description: Merchant/shop name
                category:
                  type: string
                  description: Product category
                product_url:
                  type: string
                  description: URL to the product page
                product_image_url:
                  type: string
                  description: URL to the product image
      responses:
        "200":
          description: Checkout session created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  checkout_session_id:
                    type: string
                    description: Stripe checkout session ID
                  checkout_url:
                    type: string
                    description: URL to complete the purchase
                  expires_at:
                    type: string
                    description: Session expiration timestamp
                  message:
                    type: string
                    description: Additional message (e.g., mock mode notification)

  /api/checkout/complete:
    post:
      operationId: completePurchase
      summary: Complete purchase
      description: Finalize the purchase after payment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - session_id
                - user_id
              properties:
                session_id:
                  type: string
                  description: Checkout session ID from initiateCheckout
                user_id:
                  type: string
                  description: User identifier
      responses:
        "200":
          description: Purchase completed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  invoice:
                    type: object
                    properties:
                      id:
                        type: string
                      orderId:
                        type: string
                      amount:
                        type: number
                      status:
                        type: string
                  status:
                    type: string
                    description: Purchase status (completed, pending, etc.)
                  message:
                    type: string
                    description: Success or error message

